name: Make Static Wodin Sites

runs:
  using: "composite"
  steps:
    - name: Checkout wodin config
      uses: actions/checkout@v4
      with:
        path: wodin-config

    - name: Checkout wodin
      uses: actions/checkout@v4
      with:
        ref: mrc-6023
        repository: mrc-ide/wodin
        path: wodin-builder

    - name: Run dependencies
      shell: bash
      run: |
        ./wodin-builder/scripts/run-dependencies.sh

    - name: Install npm packages
      shell: bash
      run: |
        npm ci --prefix=wodin-builder/app/static
        npm ci --prefix=wodin-builder/app/server

    - name: Build static wodin
      shell: bash
      run: |
        npm run static-build --prefix=wodin-builder/app/static

    - name: Make output folder
      shell: bash
      run: |
        mkdir static-site

    - name: Build sites
      shell: bash
      run: |
        npm run build-static-site-for-action --prefix=wodin-builder/app/server -- ../../../wodin-config ../../../static-site ./views
        npm run copy-static-files --prefix=wodin-builder/app/server

    - name: Deploy to GitHub pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        clean: false
        branch: gh-pages
        folder: static-site
